# Generated by Django 3.0.3 on 2020-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelversion',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='modelversion',
            name='votes',
        ),
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
